// Contexto dos previews do Claude Design: catalogo pt-BR e router em memoria.
// Gerado por .design-sync/gen-preview-context.mjs a partir de ArchonApiResource.pt-BR.resx. Nao editar a mao.

export const ptBRCatalog = {
  "culture": "pt-BR",
  "uiCulture": "pt-BR",
  "messages": {
    "argument.invalid": "Argumento inválido.",
    "file.content.required": "O conteúdo do arquivo é obrigatório.",
    "auth.forbidden": "Acesso negado.",
    "auth.session.invalidOrExpired": "Sessão inválida ou expirada.",
    "auth.token.validationFailed": "Falha na validação do token.",
    "auth.token.validationFailedWithDetail": "Falha na validação do token: {0}",
    "request.id.required": "O identificador é obrigatório.",
    "request.auditEntry.id.required": "O identificador do registro de auditoria é obrigatório.",
    "request.entity.id.required": "O identificador da entidade é obrigatório.",
    "request.entity.name.required": "O nome da entidade é obrigatório.",
    "operation.completed": "Operação concluída com sucesso.",
    "record.created": "Registro criado com sucesso.",
    "record.deleted": "Registro removido com sucesso.",
    "record.notFound": "Registro não encontrado.",
    "record.auditEntry.notFound": "Registro de auditoria não encontrado.",
    "record.updated": "Registro atualizado com sucesso.",
    "request.body.required": "O corpo da requisição é obrigatório.",
    "auth.unauthorized": "Não autorizado.",
    "error.unexpected": "Ocorreu um erro inesperado. Tente novamente mais tarde.",
    "error.unexpected.short": "Erro inesperado.",
    "error.integrity.violation": "Ocorreu uma violação de integridade de dados.",
    "tenant.notConfigured": "Nenhum tenant foi configurado para a requisição atual.",
    "validation.failed": "Falha de validação.",
    "validation.invalidValue": "Valor inválido.",
    "nav.about": "Sobre",
    "nav.profile": "Meu perfil",
    "nav.language": "Idioma",
    "nav.logout": "Sair",
    "nav.theme.dark": "Modo Escuro",
    "nav.theme.light": "Modo Claro",
    "common.toast.warningTitle": "Atenção",
    "common.state.noResults": "Sem resultados",
    "common.state.noRecordsFound": "Nenhum registro encontrado",
    "common.state.adjustFilters": "Ajuste filtros, paginação ou critérios de busca para continuar.",
    "common.action.cancel": "Cancelar",
    "common.action.confirm": "Confirmar",
    "common.action.search": "Buscar...",
    "common.success.title": "Sucesso",
    "common.error.title": "Erro",
    "common.error.request": "Erro na requisição",
    "common.error.connection": "Erro de conexão. Verifique sua internet.",
    "common.error.unknown": "Erro desconhecido",
    "common.error.forbidden.title": "Sem permissão",
    "common.error.forbidden.description": "Você não tem permissão para executar essa ação.",
    "common.validation.moreErrors": "E mais {0} erro(s).",
    "common.table.rowsPerPage": "Linhas por página",
    "confirmModal.title": "Confirmar ação",
    "confirmModal.description": "Tem certeza que deseja continuar?",
    "searchableSelect.placeholder": "Selecione uma opção",
    "searchableSelect.noResults": "Nenhum resultado encontrado",
    "chart.empty": "Nenhum dado disponível",
    "notifications.error.load": "Erro ao carregar notificações",
    "client.validation.single": "Erro de validação no formulário",
    "client.validation.many": "{0} erros de validação no formulário",
    "nav.openSidebar": "Abrir menu lateral",
    "nav.select": "Selecione",
    "nav.modules": "Módulos",
    "nav.notifications": "Notificações",
    "nav.notifications.unread.one": "{0} não lida",
    "nav.notifications.unread.many": "{0} não lidas",
    "nav.notifications.markAllAsRead": "Marcar como lidas",
    "nav.notifications.clearAll": "Limpar todas",
    "nav.notifications.emptyTitle": "Nenhuma notificação",
    "nav.notifications.emptyDescription": "Você está em dia!",
    "nav.notifications.viewAll": "Ver todas as notificações",
    "nav.time.now": "Agora",
    "nav.time.minutesAgo": "{0}m atrás",
    "nav.time.hoursAgo": "{0}h atrás",
    "nav.time.daysAgo": "{0}d atrás",
    "pageLayout.action.add": "Incluir",
    "pageLayout.action.view": "Visualizar",
    "pageLayout.action.edit": "Editar",
    "pageLayout.action.delete": "Excluir",
    "pageLayout.action.refresh": "Atualizar",
    "pageLayout.edit.selectOne": "Selecione um registro para editar.",
    "pageLayout.edit.selectOnlyOne": "Selecione apenas um registro para editar.",
    "pageLayout.view.selectOne": "Selecione um registro para visualizar.",
    "pageLayout.view.selectOnlyOne": "Selecione apenas um registro para visualizar.",
    "pageLayout.delete.selectAtLeastOne": "Selecione ao menos um registro para excluir.",
    "audit.area": "Auditoria",
    "audit.getByEntity.description": "Permite consultar o histórico de auditoria de uma entidade específica.",
    "audit.getById.description": "Permite consultar os detalhes de um registro específico da auditoria.",
    "audit.recent.description": "Permite listar os registros recentes de auditoria com filtros.",
    "audit.stats.description": "Permite consultar estatisticas agregadas dos registros de auditoria.",
    "notifications.area": "Notificações",
    "notifications.clearAll.description": "Permite limpar todas as notificações do usuário atual.",
    "notifications.create.description": "Permite cadastrar uma notificação.",
    "notifications.delete.description": "Permite excluir uma notificação.",
    "notifications.get.description": "Permite listar as notificações do usuário atual.",
    "notifications.getById.description": "Permite consultar uma notificação por id.",
    "notifications.getUnreadCount.description": "Permite consultar a quantidade de notificações não lidas do usuário atual.",
    "notifications.markAllAsRead.description": "Permite marcar todas as notificações do usuário atual como lidas.",
    "notifications.markAsRead.description": "Permite marcar uma notificação como lida.",
    "usersManagement.area": "Controle de acesso",
    "usersManagement.create.description": "Permite criar usuario no contrato ativo.",
    "usersManagement.createRole.description": "Permite criar um perfil no contrato ativo.",
    "usersManagement.deleteRole.description": "Permite excluir um perfil do contrato ativo.",
    "usersManagement.getAccessResources.description": "Permite listar as permissões disponíveis no contrato ativo.",
    "usersManagement.getByCurrentContract.description": "Permite listar usuarios do contrato ativo.",
    "usersManagement.getRoleById.description": "Permite consultar um perfil do contrato ativo.",
    "usersManagement.getRoles.description": "Permite listar perfis do contrato ativo.",
    "usersManagement.setActive.description": "Permite ativar/desativar usuario.",
    "usersManagement.update.description": "Permite atualizar usuario do contrato ativo.",
    "usersManagement.updateRole.description": "Permite atualizar um perfil do contrato ativo.",
    "usersManagement.getAccessCapabilities.description": "Permite listar as permissões por módulo disponíveis no contrato ativo.",
    "accessModule.usuarios": "Usuários e perfis",
    "accessModule.auditoria": "Auditoria",
    "accessModule.geral": "Geral",
    "accessCapability.usuarios.ver": "Ver usuários e perfis",
    "accessCapability.usuarios.editar": "Criar e editar usuários e perfis",
    "accessCapability.usuarios.excluir": "Excluir perfis",
    "accessCapability.auditoria.ver": "Consultar a trilha de auditoria",
    "accessCapability.geral.basico": "Acesso básico",
    "accessCapability.geral.basico.description": "Notificações e dados do próprio usuário. Incluído em todos os perfis."
  }
}

export const loadPtBRCatalog = async () => ptBRCatalog

export { MemoryRouter } from 'react-router-dom'
